import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

type D = "EASY" | "MEDIUM" | "HARD";

const PROBLEMS: {
  title: string; slug: string; difficulty: D;
  category: string; pattern: string;
  description: string; leetcodeId: number;
  totalSubmissions: number; acceptedSubmissions: number;
}[] = [
  // ── Array & Hashing ──────────────────────────────────────────────────────
  { leetcodeId: 1,   slug: "lc-1-two-sum",                    title: "Two Sum",                              difficulty: "EASY",   category: "Array", pattern: "Array & Hashing",     description: "Return indices of the two numbers that add up to target.",                                       totalSubmissions: 9800000, acceptedSubmissions: 6100000 },
  { leetcodeId: 49,  slug: "lc-49-group-anagrams",            title: "Group Anagrams",                       difficulty: "MEDIUM", category: "Array", pattern: "Array & Hashing",     description: "Group strings that are anagrams of each other.",                                                 totalSubmissions: 3200000, acceptedSubmissions: 2100000 },
  { leetcodeId: 242, slug: "lc-242-valid-anagram",            title: "Valid Anagram",                        difficulty: "EASY",   category: "Array", pattern: "Array & Hashing",     description: "Determine if two strings are anagrams.",                                                         totalSubmissions: 3600000, acceptedSubmissions: 2400000 },
  { leetcodeId: 217, slug: "lc-217-contains-duplicate",       title: "Contains Duplicate",                   difficulty: "EASY",   category: "Array", pattern: "Array & Hashing",     description: "Check if any value appears at least twice in the array.",                                        totalSubmissions: 5400000, acceptedSubmissions: 3600000 },
  { leetcodeId: 238, slug: "lc-238-product-except-self",      title: "Product of Array Except Self",         difficulty: "MEDIUM", category: "Array", pattern: "Array & Hashing",     description: "Return array where each element is product of all other elements without division.",              totalSubmissions: 2900000, acceptedSubmissions: 2100000 },
  { leetcodeId: 347, slug: "lc-347-top-k-frequent",           title: "Top K Frequent Elements",              difficulty: "MEDIUM", category: "Array", pattern: "Array & Hashing",     description: "Return the k most frequent elements.",                                                           totalSubmissions: 2700000, acceptedSubmissions: 1900000 },
  { leetcodeId: 128, slug: "lc-128-longest-consecutive",      title: "Longest Consecutive Sequence",         difficulty: "MEDIUM", category: "Array", pattern: "Array & Hashing",     description: "Find the length of the longest consecutive elements sequence.",                                   totalSubmissions: 2600000, acceptedSubmissions: 1400000 },
  { leetcodeId: 36,  slug: "lc-36-valid-sudoku",              title: "Valid Sudoku",                         difficulty: "MEDIUM", category: "Array", pattern: "Array & Hashing",     description: "Determine if a 9x9 Sudoku board is valid.",                                                      totalSubmissions: 1900000, acceptedSubmissions: 1100000 },
  { leetcodeId: 659, slug: "lc-659-encode-decode-strings",    title: "Encode and Decode Strings",            difficulty: "MEDIUM", category: "Array", pattern: "Array & Hashing",     description: "Design an algorithm to encode and decode a list of strings.",                                    totalSubmissions: 980000,  acceptedSubmissions: 640000 },

  // ── Two Pointers ──────────────────────────────────────────────────────────
  { leetcodeId: 125, slug: "lc-125-valid-palindrome",         title: "Valid Palindrome",                     difficulty: "EASY",   category: "String",  pattern: "Two Pointers",       description: "Check if a phrase is a palindrome considering only alphanumeric characters.",                    totalSubmissions: 4100000, acceptedSubmissions: 2100000 },
  { leetcodeId: 167, slug: "lc-167-two-sum-ii",               title: "Two Sum II - Input Array Is Sorted",   difficulty: "MEDIUM", category: "Array",   pattern: "Two Pointers",       description: "Find two numbers in a sorted array that sum to target.",                                         totalSubmissions: 2200000, acceptedSubmissions: 1600000 },
  { leetcodeId: 15,  slug: "lc-15-3sum",                      title: "3Sum",                                 difficulty: "MEDIUM", category: "Array",   pattern: "Two Pointers",       description: "Find all unique triplets that sum to zero.",                                                     totalSubmissions: 7100000, acceptedSubmissions: 3000000 },
  { leetcodeId: 11,  slug: "lc-11-container-with-most-water", title: "Container With Most Water",            difficulty: "MEDIUM", category: "Array",   pattern: "Two Pointers",       description: "Find two lines that together with x-axis forms a container holding the most water.",             totalSubmissions: 4600000, acceptedSubmissions: 2900000 },
  { leetcodeId: 42,  slug: "lc-42-trapping-rain-water",       title: "Trapping Rain Water",                  difficulty: "HARD",   category: "Array",   pattern: "Two Pointers",       description: "Compute how much water can be trapped after raining.",                                           totalSubmissions: 4500000, acceptedSubmissions: 2900000 },
  { leetcodeId: 18,  slug: "lc-18-4sum",                      title: "4Sum",                                 difficulty: "MEDIUM", category: "Array",   pattern: "Two Pointers",       description: "Find all unique quadruplets that sum to target.",                                                totalSubmissions: 1800000, acceptedSubmissions: 820000 },

  // ── Sliding Window ────────────────────────────────────────────────────────
  { leetcodeId: 121, slug: "lc-121-best-time-to-buy",         title: "Best Time to Buy and Sell Stock",      difficulty: "EASY",   category: "Array",   pattern: "Sliding Window",     description: "Find the maximum profit from a single buy and sell.",                                            totalSubmissions: 8200000, acceptedSubmissions: 5500000 },
  { leetcodeId: 3,   slug: "lc-3-longest-substring",          title: "Longest Substring Without Repeating",  difficulty: "MEDIUM", category: "String",  pattern: "Sliding Window",     description: "Find the length of the longest substring without repeating characters.",                        totalSubmissions: 8900000, acceptedSubmissions: 4200000 },
  { leetcodeId: 424, slug: "lc-424-longest-repeating-char",   title: "Longest Repeating Character Replacement", difficulty: "MEDIUM", category: "String", pattern: "Sliding Window",  description: "Find length of longest substring containing same letter after at most k replacements.",          totalSubmissions: 1800000, acceptedSubmissions: 1000000 },
  { leetcodeId: 567, slug: "lc-567-permutation-in-string",    title: "Permutation in String",                difficulty: "MEDIUM", category: "String",  pattern: "Sliding Window",     description: "Check if s1's permutation is a substring of s2.",                                               totalSubmissions: 1700000, acceptedSubmissions: 950000 },
  { leetcodeId: 76,  slug: "lc-76-minimum-window-substring",  title: "Minimum Window Substring",             difficulty: "HARD",   category: "String",  pattern: "Sliding Window",     description: "Find the minimum window in s which contains all characters of t.",                               totalSubmissions: 2900000, acceptedSubmissions: 1200000 },
  { leetcodeId: 239, slug: "lc-239-sliding-window-maximum",   title: "Sliding Window Maximum",               difficulty: "HARD",   category: "Array",   pattern: "Sliding Window",     description: "Find maximum value in each sliding window of size k.",                                          totalSubmissions: 1600000, acceptedSubmissions: 810000 },

  // ── Stack ─────────────────────────────────────────────────────────────────
  { leetcodeId: 20,  slug: "lc-20-valid-parentheses",         title: "Valid Parentheses",                    difficulty: "EASY",   category: "Stack",   pattern: "Stack",              description: "Determine if the input string of brackets is valid.",                                            totalSubmissions: 7800000, acceptedSubmissions: 3900000 },
  { leetcodeId: 155, slug: "lc-155-min-stack",                title: "Min Stack",                            difficulty: "MEDIUM", category: "Stack",   pattern: "Stack",              description: "Design a stack that retrieves the minimum element in O(1).",                                     totalSubmissions: 2800000, acceptedSubmissions: 1800000 },
  { leetcodeId: 150, slug: "lc-150-evaluate-rpn",             title: "Evaluate Reverse Polish Notation",     difficulty: "MEDIUM", category: "Stack",   pattern: "Stack",              description: "Evaluate the value of an arithmetic expression in RPN.",                                         totalSubmissions: 1800000, acceptedSubmissions: 1100000 },
  { leetcodeId: 22,  slug: "lc-22-generate-parentheses",      title: "Generate Parentheses",                 difficulty: "MEDIUM", category: "Stack",   pattern: "Stack",              description: "Generate all combinations of well-formed parentheses.",                                          totalSubmissions: 3400000, acceptedSubmissions: 2500000 },
  { leetcodeId: 739, slug: "lc-739-daily-temperatures",       title: "Daily Temperatures",                   difficulty: "MEDIUM", category: "Stack",   pattern: "Stack",              description: "For each day find how many days until a warmer temperature.",                                    totalSubmissions: 2700000, acceptedSubmissions: 1900000 },
  { leetcodeId: 853, slug: "lc-853-car-fleet",                title: "Car Fleet",                            difficulty: "MEDIUM", category: "Stack",   pattern: "Stack",              description: "Find the number of car fleets that arrive at the destination.",                                  totalSubmissions: 1100000, acceptedSubmissions: 690000 },
  { leetcodeId: 84,  slug: "lc-84-largest-rectangle",         title: "Largest Rectangle in Histogram",       difficulty: "HARD",   category: "Stack",   pattern: "Stack",              description: "Find the largest rectangle in a histogram.",                                                    totalSubmissions: 2600000, acceptedSubmissions: 1200000 },

  // ── Binary Search ─────────────────────────────────────────────────────────
  { leetcodeId: 704, slug: "lc-704-binary-search",            title: "Binary Search",                        difficulty: "EASY",   category: "Array",   pattern: "Binary Search",      description: "Implement binary search on a sorted array.",                                                    totalSubmissions: 3400000, acceptedSubmissions: 2500000 },
  { leetcodeId: 74,  slug: "lc-74-search-2d-matrix",          title: "Search a 2D Matrix",                   difficulty: "MEDIUM", category: "Matrix",  pattern: "Binary Search",      description: "Search for a value in an m×n matrix with sorted rows and columns.",                             totalSubmissions: 2100000, acceptedSubmissions: 1400000 },
  { leetcodeId: 875, slug: "lc-875-koko-eating-bananas",      title: "Koko Eating Bananas",                  difficulty: "MEDIUM", category: "Array",   pattern: "Binary Search",      description: "Find the minimum eating speed to finish all bananas within h hours.",                           totalSubmissions: 1400000, acceptedSubmissions: 870000 },
  { leetcodeId: 33,  slug: "lc-33-search-rotated-array",      title: "Search in Rotated Sorted Array",       difficulty: "MEDIUM", category: "Array",   pattern: "Binary Search",      description: "Search target in a sorted array that has been rotated.",                                        totalSubmissions: 4500000, acceptedSubmissions: 2300000 },
  { leetcodeId: 153, slug: "lc-153-find-minimum-rotated",     title: "Find Minimum in Rotated Sorted Array", difficulty: "MEDIUM", category: "Array",   pattern: "Binary Search",      description: "Find the minimum element in a rotated sorted array.",                                           totalSubmissions: 3200000, acceptedSubmissions: 2100000 },
  { leetcodeId: 981, slug: "lc-981-time-based-key-value",     title: "Time Based Key-Value Store",           difficulty: "MEDIUM", category: "Design",  pattern: "Binary Search",      description: "Design a time-based key-value data structure.",                                                 totalSubmissions: 870000,  acceptedSubmissions: 600000 },
  { leetcodeId: 4,   slug: "lc-4-median-two-sorted-arrays",   title: "Median of Two Sorted Arrays",          difficulty: "HARD",   category: "Array",   pattern: "Binary Search",      description: "Find the median of two sorted arrays in O(log(m+n)) time.",                                    totalSubmissions: 5500000, acceptedSubmissions: 2200000 },

  // ── Linked List ───────────────────────────────────────────────────────────
  { leetcodeId: 206, slug: "lc-206-reverse-linked-list",      title: "Reverse Linked List",                  difficulty: "EASY",   category: "Linked List", pattern: "Linked List",    description: "Reverse a singly linked list.",                                                                 totalSubmissions: 7200000, acceptedSubmissions: 5300000 },
  { leetcodeId: 21,  slug: "lc-21-merge-two-sorted-lists",    title: "Merge Two Sorted Lists",               difficulty: "EASY",   category: "Linked List", pattern: "Linked List",    description: "Merge two sorted linked lists into one sorted list.",                                           totalSubmissions: 6500000, acceptedSubmissions: 4500000 },
  { leetcodeId: 143, slug: "lc-143-reorder-list",             title: "Reorder List",                         difficulty: "MEDIUM", category: "Linked List", pattern: "Linked List",    description: "Reorder list so it follows L0→Ln→L1→Ln-1→L2→Ln-2→…",                                          totalSubmissions: 1700000, acceptedSubmissions: 1000000 },
  { leetcodeId: 19,  slug: "lc-19-remove-nth-from-end",       title: "Remove Nth Node From End of List",     difficulty: "MEDIUM", category: "Linked List", pattern: "Linked List",    description: "Remove the nth node from the end of the linked list.",                                          totalSubmissions: 4200000, acceptedSubmissions: 2400000 },
  { leetcodeId: 138, slug: "lc-138-copy-list-random-pointer", title: "Copy List with Random Pointer",        difficulty: "MEDIUM", category: "Linked List", pattern: "Linked List",    description: "Deep copy a linked list with next and random pointers.",                                        totalSubmissions: 2600000, acceptedSubmissions: 1600000 },
  { leetcodeId: 2,   slug: "lc-2-add-two-numbers",            title: "Add Two Numbers",                      difficulty: "MEDIUM", category: "Linked List", pattern: "Linked List",    description: "Add two numbers represented as reversed linked lists.",                                         totalSubmissions: 6700000, acceptedSubmissions: 3700000 },
  { leetcodeId: 141, slug: "lc-141-linked-list-cycle",        title: "Linked List Cycle",                    difficulty: "EASY",   category: "Linked List", pattern: "Linked List",    description: "Detect if a linked list has a cycle.",                                                          totalSubmissions: 5700000, acceptedSubmissions: 3600000 },
  { leetcodeId: 287, slug: "lc-287-find-duplicate",           title: "Find the Duplicate Number",            difficulty: "MEDIUM", category: "Linked List", pattern: "Linked List",    description: "Find the duplicate number in an array using Floyd's cycle detection.",                          totalSubmissions: 2700000, acceptedSubmissions: 1800000 },
  { leetcodeId: 23,  slug: "lc-23-merge-k-sorted-lists",      title: "Merge K Sorted Lists",                 difficulty: "HARD",   category: "Linked List", pattern: "Linked List",    description: "Merge k sorted linked lists into one sorted list.",                                             totalSubmissions: 3200000, acceptedSubmissions: 1700000 },
  { leetcodeId: 25,  slug: "lc-25-reverse-k-group",           title: "Reverse Nodes in k-Group",             difficulty: "HARD",   category: "Linked List", pattern: "Linked List",    description: "Reverse nodes in k-group in a linked list.",                                                    totalSubmissions: 2100000, acceptedSubmissions: 1200000 },

  // ── Trees ─────────────────────────────────────────────────────────────────
  { leetcodeId: 226, slug: "lc-226-invert-binary-tree",       title: "Invert Binary Tree",                   difficulty: "EASY",   category: "Tree",    pattern: "Trees",              description: "Invert a binary tree.",                                                                         totalSubmissions: 5400000, acceptedSubmissions: 4200000 },
  { leetcodeId: 104, slug: "lc-104-max-depth-tree",           title: "Maximum Depth of Binary Tree",         difficulty: "EASY",   category: "Tree",    pattern: "Trees",              description: "Find the maximum depth of a binary tree.",                                                      totalSubmissions: 6300000, acceptedSubmissions: 4900000 },
  { leetcodeId: 543, slug: "lc-543-diameter-binary-tree",     title: "Diameter of Binary Tree",              difficulty: "EASY",   category: "Tree",    pattern: "Trees",              description: "Find the length of the diameter of a binary tree.",                                             totalSubmissions: 4100000, acceptedSubmissions: 3100000 },
  { leetcodeId: 110, slug: "lc-110-balanced-binary-tree",     title: "Balanced Binary Tree",                 difficulty: "EASY",   category: "Tree",    pattern: "Trees",              description: "Determine if a binary tree is height-balanced.",                                                totalSubmissions: 4600000, acceptedSubmissions: 3100000 },
  { leetcodeId: 100, slug: "lc-100-same-tree",                title: "Same Tree",                            difficulty: "EASY",   category: "Tree",    pattern: "Trees",              description: "Check if two binary trees are structurally identical and have same node values.",               totalSubmissions: 4800000, acceptedSubmissions: 3400000 },
  { leetcodeId: 572, slug: "lc-572-subtree-of-another",       title: "Subtree of Another Tree",              difficulty: "EASY",   category: "Tree",    pattern: "Trees",              description: "Check if a tree is a subtree of another tree.",                                                 totalSubmissions: 3000000, acceptedSubmissions: 1900000 },
  { leetcodeId: 235, slug: "lc-235-lca-bst",                  title: "Lowest Common Ancestor of a BST",      difficulty: "MEDIUM", category: "Tree",    pattern: "Trees",              description: "Find the lowest common ancestor of two nodes in a BST.",                                        totalSubmissions: 3700000, acceptedSubmissions: 2800000 },
  { leetcodeId: 102, slug: "lc-102-level-order-traversal",    title: "Binary Tree Level Order Traversal",    difficulty: "MEDIUM", category: "Tree",    pattern: "Trees",              description: "Return the level order traversal of a binary tree's values.",                                   totalSubmissions: 5000000, acceptedSubmissions: 3600000 },
  { leetcodeId: 199, slug: "lc-199-right-side-view",          title: "Binary Tree Right Side View",          difficulty: "MEDIUM", category: "Tree",    pattern: "Trees",              description: "Return values visible from the right side of a binary tree.",                                   totalSubmissions: 2800000, acceptedSubmissions: 2000000 },
  { leetcodeId: 1448, slug: "lc-1448-count-good-nodes",       title: "Count Good Nodes in Binary Tree",      difficulty: "MEDIUM", category: "Tree",    pattern: "Trees",              description: "Count nodes where no node in the path from root has a greater value.",                          totalSubmissions: 990000,  acceptedSubmissions: 770000 },
  { leetcodeId: 98,  slug: "lc-98-validate-bst",              title: "Validate Binary Search Tree",          difficulty: "MEDIUM", category: "Tree",    pattern: "Trees",              description: "Determine if a binary tree is a valid BST.",                                                    totalSubmissions: 5100000, acceptedSubmissions: 2800000 },
  { leetcodeId: 230, slug: "lc-230-kth-smallest-bst",         title: "Kth Smallest Element in a BST",        difficulty: "MEDIUM", category: "Tree",    pattern: "Trees",              description: "Find the kth smallest element in a BST.",                                                       totalSubmissions: 2400000, acceptedSubmissions: 1900000 },
  { leetcodeId: 105, slug: "lc-105-construct-from-preorder",  title: "Construct Tree from Preorder&Inorder", difficulty: "MEDIUM", category: "Tree",    pattern: "Trees",              description: "Build a binary tree from preorder and inorder traversal.",                                      totalSubmissions: 3200000, acceptedSubmissions: 2200000 },
  { leetcodeId: 124, slug: "lc-124-binary-tree-max-path",     title: "Binary Tree Maximum Path Sum",         difficulty: "HARD",   category: "Tree",    pattern: "Trees",              description: "Find the maximum path sum in a binary tree.",                                                   totalSubmissions: 3100000, acceptedSubmissions: 1600000 },
  { leetcodeId: 297, slug: "lc-297-serialize-deserialize",    title: "Serialize and Deserialize Binary Tree",difficulty: "HARD",   category: "Tree",    pattern: "Trees",              description: "Design an algorithm to serialize and deserialize a binary tree.",                               totalSubmissions: 2100000, acceptedSubmissions: 1200000 },

  // ── Tries ─────────────────────────────────────────────────────────────────
  { leetcodeId: 208, slug: "lc-208-implement-trie",           title: "Implement Trie (Prefix Tree)",         difficulty: "MEDIUM", category: "Trie",    pattern: "Tries",              description: "Implement a trie with insert, search, and startsWith methods.",                                 totalSubmissions: 2100000, acceptedSubmissions: 1500000 },
  { leetcodeId: 211, slug: "lc-211-design-add-search-words",  title: "Design Add and Search Words Data Structure", difficulty: "MEDIUM", category: "Trie", pattern: "Tries",          description: "Design a data structure that supports adding words and searching with wildcards.",               totalSubmissions: 1300000, acceptedSubmissions: 800000 },
  { leetcodeId: 212, slug: "lc-212-word-search-ii",           title: "Word Search II",                       difficulty: "HARD",   category: "Trie",    pattern: "Tries",              description: "Find all words from a dictionary that can be constructed in a board.",                          totalSubmissions: 1500000, acceptedSubmissions: 580000 },

  // ── Heap / Priority Queue ─────────────────────────────────────────────────
  { leetcodeId: 703, slug: "lc-703-kth-largest-stream",       title: "Kth Largest Element in a Stream",      difficulty: "EASY",   category: "Heap",    pattern: "Heap / Priority Queue", description: "Design a class to find the kth largest element in a stream.",                                totalSubmissions: 1600000, acceptedSubmissions: 1100000 },
  { leetcodeId: 1046, slug: "lc-1046-last-stone-weight",      title: "Last Stone Weight",                    difficulty: "EASY",   category: "Heap",    pattern: "Heap / Priority Queue", description: "Simulate stone smashing using a max heap.",                                                  totalSubmissions: 1800000, acceptedSubmissions: 1300000 },
  { leetcodeId: 973, slug: "lc-973-k-closest-points",         title: "K Closest Points to Origin",           difficulty: "MEDIUM", category: "Heap",    pattern: "Heap / Priority Queue", description: "Find k points closest to the origin.",                                                       totalSubmissions: 2800000, acceptedSubmissions: 2100000 },
  { leetcodeId: 215, slug: "lc-215-kth-largest-array",        title: "Kth Largest Element in an Array",      difficulty: "MEDIUM", category: "Heap",    pattern: "Heap / Priority Queue", description: "Find the kth largest element in an unsorted array.",                                         totalSubmissions: 4200000, acceptedSubmissions: 2900000 },
  { leetcodeId: 621, slug: "lc-621-task-scheduler",           title: "Task Scheduler",                       difficulty: "MEDIUM", category: "Heap",    pattern: "Heap / Priority Queue", description: "Find minimum intervals needed to execute all tasks with cooldown n.",                         totalSubmissions: 1700000, acceptedSubmissions: 1000000 },
  { leetcodeId: 355, slug: "lc-355-design-twitter",           title: "Design Twitter",                       difficulty: "MEDIUM", category: "Design",  pattern: "Heap / Priority Queue", description: "Design a simplified version of Twitter.",                                                    totalSubmissions: 1100000, acceptedSubmissions: 630000 },
  { leetcodeId: 295, slug: "lc-295-find-median-data-stream",  title: "Find Median from Data Stream",         difficulty: "HARD",   category: "Heap",    pattern: "Heap / Priority Queue", description: "Find the median of a data stream using two heaps.",                                          totalSubmissions: 2200000, acceptedSubmissions: 1300000 },

  // ── Backtracking ──────────────────────────────────────────────────────────
  { leetcodeId: 78,  slug: "lc-78-subsets",                   title: "Subsets",                              difficulty: "MEDIUM", category: "Backtracking", pattern: "Backtracking",   description: "Return all possible subsets of an integer array.",                                             totalSubmissions: 3600000, acceptedSubmissions: 2800000 },
  { leetcodeId: 39,  slug: "lc-39-combination-sum",           title: "Combination Sum",                      difficulty: "MEDIUM", category: "Backtracking", pattern: "Backtracking",   description: "Find all combinations that sum to target (reuse allowed).",                                    totalSubmissions: 4400000, acceptedSubmissions: 3300000 },
  { leetcodeId: 40,  slug: "lc-40-combination-sum-ii",        title: "Combination Sum II",                   difficulty: "MEDIUM", category: "Backtracking", pattern: "Backtracking",   description: "Find all unique combinations that sum to target (each number once).",                         totalSubmissions: 2600000, acceptedSubmissions: 1700000 },
  { leetcodeId: 46,  slug: "lc-46-permutations",              title: "Permutations",                         difficulty: "MEDIUM", category: "Backtracking", pattern: "Backtracking",   description: "Return all possible permutations of a distinct integer array.",                               totalSubmissions: 4200000, acceptedSubmissions: 3300000 },
  { leetcodeId: 90,  slug: "lc-90-subsets-ii",                title: "Subsets II",                           difficulty: "MEDIUM", category: "Backtracking", pattern: "Backtracking",   description: "Return all subsets of an array that may contain duplicates.",                                 totalSubmissions: 2100000, acceptedSubmissions: 1500000 },
  { leetcodeId: 79,  slug: "lc-79-word-search",               title: "Word Search",                          difficulty: "MEDIUM", category: "Backtracking", pattern: "Backtracking",   description: "Check if a word exists in a grid using adjacent cells.",                                      totalSubmissions: 4700000, acceptedSubmissions: 2100000 },
  { leetcodeId: 131, slug: "lc-131-palindrome-partitioning",  title: "Palindrome Partitioning",              difficulty: "MEDIUM", category: "Backtracking", pattern: "Backtracking",   description: "Partition a string so every substring is a palindrome.",                                      totalSubmissions: 1900000, acceptedSubmissions: 1400000 },
  { leetcodeId: 17,  slug: "lc-17-letter-combinations",       title: "Letter Combinations of a Phone Number",difficulty: "MEDIUM", category: "Backtracking", pattern: "Backtracking",   description: "Return all possible letter combinations from a phone digit string.",                          totalSubmissions: 4500000, acceptedSubmissions: 3200000 },
  { leetcodeId: 51,  slug: "lc-51-n-queens",                  title: "N-Queens",                             difficulty: "HARD",   category: "Backtracking", pattern: "Backtracking",   description: "Place n queens on an n×n chessboard so no two queens attack each other.",                    totalSubmissions: 2100000, acceptedSubmissions: 1500000 },

  // ── Graphs ────────────────────────────────────────────────────────────────
  { leetcodeId: 200, slug: "lc-200-number-of-islands",        title: "Number of Islands",                    difficulty: "MEDIUM", category: "Graph",   pattern: "Graphs",             description: "Count the number of islands in a 2D grid.",                                                    totalSubmissions: 6900000, acceptedSubmissions: 4100000 },
  { leetcodeId: 133, slug: "lc-133-clone-graph",              title: "Clone Graph",                          difficulty: "MEDIUM", category: "Graph",   pattern: "Graphs",             description: "Return a deep copy of the graph.",                                                              totalSubmissions: 2200000, acceptedSubmissions: 1400000 },
  { leetcodeId: 695, slug: "lc-695-max-area-of-island",       title: "Max Area of Island",                   difficulty: "MEDIUM", category: "Graph",   pattern: "Graphs",             description: "Find the maximum area of an island in a 2D grid.",                                             totalSubmissions: 2500000, acceptedSubmissions: 1900000 },
  { leetcodeId: 417, slug: "lc-417-pacific-atlantic",         title: "Pacific Atlantic Water Flow",          difficulty: "MEDIUM", category: "Graph",   pattern: "Graphs",             description: "Find cells from which water flows to both Pacific and Atlantic oceans.",                       totalSubmissions: 1700000, acceptedSubmissions: 1000000 },
  { leetcodeId: 130, slug: "lc-130-surrounded-regions",       title: "Surrounded Regions",                   difficulty: "MEDIUM", category: "Graph",   pattern: "Graphs",             description: "Capture all 'O' regions surrounded by 'X'.",                                                   totalSubmissions: 1900000, acceptedSubmissions: 960000 },
  { leetcodeId: 207, slug: "lc-207-course-schedule",          title: "Course Schedule",                      difficulty: "MEDIUM", category: "Graph",   pattern: "Graphs",             description: "Determine if you can finish all courses given prerequisites (cycle detection).",               totalSubmissions: 3700000, acceptedSubmissions: 2100000 },
  { leetcodeId: 210, slug: "lc-210-course-schedule-ii",       title: "Course Schedule II",                   difficulty: "MEDIUM", category: "Graph",   pattern: "Graphs",             description: "Return the ordering of courses to finish all (topological sort).",                             totalSubmissions: 2600000, acceptedSubmissions: 1500000 },
  { leetcodeId: 994, slug: "lc-994-rotting-oranges",          title: "Rotting Oranges",                      difficulty: "MEDIUM", category: "Graph",   pattern: "Graphs",             description: "Find the minimum time to rot all oranges using multi-source BFS.",                             totalSubmissions: 2500000, acceptedSubmissions: 1400000 },
  { leetcodeId: 286, slug: "lc-286-walls-and-gates",          title: "Walls and Gates",                      difficulty: "MEDIUM", category: "Graph",   pattern: "Graphs",             description: "Fill each empty room with distance to nearest gate.",                                          totalSubmissions: 970000,  acceptedSubmissions: 620000 },
  { leetcodeId: 323, slug: "lc-323-connected-components",     title: "Number of Connected Components",       difficulty: "MEDIUM", category: "Graph",   pattern: "Graphs",             description: "Find number of connected components in an undirected graph.",                                  totalSubmissions: 980000,  acceptedSubmissions: 700000 },
  { leetcodeId: 684, slug: "lc-684-redundant-connection",     title: "Redundant Connection",                 difficulty: "MEDIUM", category: "Graph",   pattern: "Graphs",             description: "Find the edge that can be removed to make a valid tree.",                                      totalSubmissions: 1200000, acceptedSubmissions: 820000 },
  { leetcodeId: 127, slug: "lc-127-word-ladder",              title: "Word Ladder",                          difficulty: "HARD",   category: "Graph",   pattern: "Graphs",             description: "Find shortest transformation sequence from beginWord to endWord.",                             totalSubmissions: 2800000, acceptedSubmissions: 1000000 },

  // ── Dynamic Programming (1D) ──────────────────────────────────────────────
  { leetcodeId: 70,  slug: "lc-70-climbing-stairs",           title: "Climbing Stairs",                      difficulty: "EASY",   category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Count ways to reach the top of n stairs (1 or 2 steps).",              totalSubmissions: 7900000, acceptedSubmissions: 5800000 },
  { leetcodeId: 746, slug: "lc-746-min-cost-climbing-stairs", title: "Min Cost Climbing Stairs",             difficulty: "EASY",   category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Find minimum cost to reach the top of the staircase.",                  totalSubmissions: 3100000, acceptedSubmissions: 2400000 },
  { leetcodeId: 198, slug: "lc-198-house-robber",             title: "House Robber",                         difficulty: "MEDIUM", category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Rob houses without robbing adjacent ones to maximize profit.",           totalSubmissions: 5700000, acceptedSubmissions: 3900000 },
  { leetcodeId: 213, slug: "lc-213-house-robber-ii",          title: "House Robber II",                      difficulty: "MEDIUM", category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Rob houses arranged in a circle.",                                       totalSubmissions: 2900000, acceptedSubmissions: 1900000 },
  { leetcodeId: 5,   slug: "lc-5-longest-palindromic-substr", title: "Longest Palindromic Substring",        difficulty: "MEDIUM", category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Find the longest palindromic substring.",                                totalSubmissions: 6600000, acceptedSubmissions: 3000000 },
  { leetcodeId: 647, slug: "lc-647-palindromic-substrings",   title: "Palindromic Substrings",               difficulty: "MEDIUM", category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Count all palindromic substrings.",                                      totalSubmissions: 2400000, acceptedSubmissions: 1800000 },
  { leetcodeId: 91,  slug: "lc-91-decode-ways",               title: "Decode Ways",                          difficulty: "MEDIUM", category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Count the number of ways to decode an encoded message.",                 totalSubmissions: 4200000, acceptedSubmissions: 2100000 },
  { leetcodeId: 322, slug: "lc-322-coin-change",              title: "Coin Change",                          difficulty: "MEDIUM", category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Find the minimum number of coins needed to make the amount.",            totalSubmissions: 5100000, acceptedSubmissions: 2700000 },
  { leetcodeId: 139, slug: "lc-139-word-break",               title: "Word Break",                           difficulty: "MEDIUM", category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Determine if the string can be segmented into dictionary words.",         totalSubmissions: 4800000, acceptedSubmissions: 2800000 },
  { leetcodeId: 300, slug: "lc-300-longest-increasing-subseq",title: "Longest Increasing Subsequence",       difficulty: "MEDIUM", category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Find length of the longest strictly increasing subsequence.",            totalSubmissions: 4700000, acceptedSubmissions: 2900000 },
  { leetcodeId: 416, slug: "lc-416-partition-equal-subset",   title: "Partition Equal Subset Sum",           difficulty: "MEDIUM", category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Determine if array can be partitioned into two equal-sum subsets.",      totalSubmissions: 2700000, acceptedSubmissions: 1500000 },

  // ── Dynamic Programming (2D) ──────────────────────────────────────────────
  { leetcodeId: 62,  slug: "lc-62-unique-paths",              title: "Unique Paths",                         difficulty: "MEDIUM", category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Count paths in an m×n grid from top-left to bottom-right.",              totalSubmissions: 4100000, acceptedSubmissions: 3200000 },
  { leetcodeId: 1143, slug: "lc-1143-lcs",                    title: "Longest Common Subsequence",           difficulty: "MEDIUM", category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Find the length of the longest common subsequence of two strings.",       totalSubmissions: 2900000, acceptedSubmissions: 2000000 },
  { leetcodeId: 309, slug: "lc-309-stock-with-cooldown",      title: "Best Time to Buy Stock with Cooldown", difficulty: "MEDIUM", category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Maximize profit with a cooldown period between transactions.",            totalSubmissions: 1700000, acceptedSubmissions: 1200000 },
  { leetcodeId: 518, slug: "lc-518-coin-change-ii",           title: "Coin Change II",                       difficulty: "MEDIUM", category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Count the number of ways to make up the amount.",                        totalSubmissions: 1900000, acceptedSubmissions: 1400000 },
  { leetcodeId: 494, slug: "lc-494-target-sum",               title: "Target Sum",                           difficulty: "MEDIUM", category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Count ways to assign + and - to reach target sum.",                      totalSubmissions: 2600000, acceptedSubmissions: 1700000 },
  { leetcodeId: 97,  slug: "lc-97-interleaving-string",       title: "Interleaving String",                  difficulty: "MEDIUM", category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Check if s3 is formed by interleaving s1 and s2.",                       totalSubmissions: 1500000, acceptedSubmissions: 830000 },
  { leetcodeId: 329, slug: "lc-329-longest-increasing-path",  title: "Longest Increasing Path in Matrix",    difficulty: "HARD",   category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Find the longest increasing path in a matrix.",                          totalSubmissions: 1400000, acceptedSubmissions: 820000 },
  { leetcodeId: 115, slug: "lc-115-distinct-subsequences",    title: "Distinct Subsequences",                difficulty: "HARD",   category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Count distinct subsequences of s which equals t.",                       totalSubmissions: 1400000, acceptedSubmissions: 720000 },
  { leetcodeId: 72,  slug: "lc-72-edit-distance",             title: "Edit Distance",                        difficulty: "MEDIUM", category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Find minimum operations to convert word1 to word2.",                    totalSubmissions: 3500000, acceptedSubmissions: 2200000 },
  { leetcodeId: 312, slug: "lc-312-burst-balloons",           title: "Burst Balloons",                       difficulty: "HARD",   category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Maximize coins by bursting balloons optimally.",                         totalSubmissions: 1100000, acceptedSubmissions: 720000 },
  { leetcodeId: 10,  slug: "lc-10-regular-expression",        title: "Regular Expression Matching",          difficulty: "HARD",   category: "Dynamic Programming", pattern: "Dynamic Programming", description: "Implement regular expression matching with '.' and '*'.",               totalSubmissions: 2400000, acceptedSubmissions: 970000 },

  // ── Greedy ────────────────────────────────────────────────────────────────
  { leetcodeId: 53,  slug: "lc-53-maximum-subarray",          title: "Maximum Subarray",                     difficulty: "MEDIUM", category: "Array",   pattern: "Greedy",             description: "Find the subarray with the largest sum.",                                                      totalSubmissions: 8600000, acceptedSubmissions: 6100000 },
  { leetcodeId: 55,  slug: "lc-55-jump-game",                 title: "Jump Game",                            difficulty: "MEDIUM", category: "Array",   pattern: "Greedy",             description: "Determine if you can reach the last index.",                                                   totalSubmissions: 5000000, acceptedSubmissions: 3200000 },
  { leetcodeId: 45,  slug: "lc-45-jump-game-ii",              title: "Jump Game II",                         difficulty: "MEDIUM", category: "Array",   pattern: "Greedy",             description: "Find the minimum jumps to reach the last index.",                                              totalSubmissions: 3200000, acceptedSubmissions: 2100000 },
  { leetcodeId: 134, slug: "lc-134-gas-station",              title: "Gas Station",                          difficulty: "MEDIUM", category: "Array",   pattern: "Greedy",             description: "Find the starting gas station to complete a circuit.",                                        totalSubmissions: 2500000, acceptedSubmissions: 1500000 },
  { leetcodeId: 846, slug: "lc-846-hand-of-straights",        title: "Hand of Straights",                    difficulty: "MEDIUM", category: "Array",   pattern: "Greedy",             description: "Check if cards can be rearranged into groups of consecutive cards.",                          totalSubmissions: 860000,  acceptedSubmissions: 550000 },
  { leetcodeId: 1899, slug: "lc-1899-merge-triplets",         title: "Merge Triplets to Form Target Triplet",difficulty: "MEDIUM", category: "Array",   pattern: "Greedy",             description: "Determine if target triplet can be formed from given triplets.",                               totalSubmissions: 640000,  acceptedSubmissions: 480000 },
  { leetcodeId: 763, slug: "lc-763-partition-labels",         title: "Partition Labels",                     difficulty: "MEDIUM", category: "String",  pattern: "Greedy",             description: "Partition a string into as many parts as possible where each letter appears in at most one part.", totalSubmissions: 1900000, acceptedSubmissions: 1600000 },
  { leetcodeId: 678, slug: "lc-678-valid-parenthesis-string", title: "Valid Parenthesis String",             difficulty: "MEDIUM", category: "Stack",   pattern: "Greedy",             description: "Check if string with '*' is valid parenthesis.",                                              totalSubmissions: 1500000, acceptedSubmissions: 870000 },

  // ── Intervals ─────────────────────────────────────────────────────────────
  { leetcodeId: 57,  slug: "lc-57-insert-interval",           title: "Insert Interval",                      difficulty: "MEDIUM", category: "Array",   pattern: "Intervals",          description: "Insert a new interval into sorted non-overlapping intervals.",                                 totalSubmissions: 2500000, acceptedSubmissions: 1400000 },
  { leetcodeId: 56,  slug: "lc-56-merge-intervals",           title: "Merge Intervals",                      difficulty: "MEDIUM", category: "Array",   pattern: "Intervals",          description: "Merge all overlapping intervals.",                                                             totalSubmissions: 5400000, acceptedSubmissions: 3100000 },
  { leetcodeId: 435, slug: "lc-435-non-overlapping-intervals",title: "Non-overlapping Intervals",            difficulty: "MEDIUM", category: "Array",   pattern: "Intervals",          description: "Find minimum number of intervals to remove to make the rest non-overlapping.",                totalSubmissions: 2100000, acceptedSubmissions: 1300000 },
  { leetcodeId: 252, slug: "lc-252-meeting-rooms",            title: "Meeting Rooms",                        difficulty: "EASY",   category: "Array",   pattern: "Intervals",          description: "Determine if a person could attend all meetings.",                                             totalSubmissions: 960000,  acceptedSubmissions: 730000 },
  { leetcodeId: 253, slug: "lc-253-meeting-rooms-ii",         title: "Meeting Rooms II",                     difficulty: "MEDIUM", category: "Array",   pattern: "Intervals",          description: "Find the minimum number of conference rooms required.",                                        totalSubmissions: 1200000, acceptedSubmissions: 810000 },
  { leetcodeId: 1851, slug: "lc-1851-minimum-interval",       title: "Minimum Interval to Include Each Query", difficulty: "HARD", category: "Array",  pattern: "Intervals",          description: "For each query, find the smallest interval that contains it.",                                totalSubmissions: 460000,  acceptedSubmissions: 250000 },

  // ── Math & Geometry ───────────────────────────────────────────────────────
  { leetcodeId: 48,  slug: "lc-48-rotate-image",              title: "Rotate Image",                         difficulty: "MEDIUM", category: "Matrix",  pattern: "Math & Geometry",    description: "Rotate an n×n matrix 90 degrees clockwise in-place.",                                         totalSubmissions: 3600000, acceptedSubmissions: 2800000 },
  { leetcodeId: 54,  slug: "lc-54-spiral-matrix",             title: "Spiral Matrix",                        difficulty: "MEDIUM", category: "Matrix",  pattern: "Math & Geometry",    description: "Return all elements of a matrix in spiral order.",                                             totalSubmissions: 3900000, acceptedSubmissions: 2500000 },
  { leetcodeId: 73,  slug: "lc-73-set-matrix-zeroes",         title: "Set Matrix Zeroes",                    difficulty: "MEDIUM", category: "Matrix",  pattern: "Math & Geometry",    description: "Set entire row and column to 0 when an element is 0.",                                        totalSubmissions: 3300000, acceptedSubmissions: 2300000 },
  { leetcodeId: 202, slug: "lc-202-happy-number",             title: "Happy Number",                         difficulty: "EASY",   category: "Math",    pattern: "Math & Geometry",    description: "Determine if a number is a happy number.",                                                     totalSubmissions: 3700000, acceptedSubmissions: 2700000 },
  { leetcodeId: 66,  slug: "lc-66-plus-one",                  title: "Plus One",                             difficulty: "EASY",   category: "Math",    pattern: "Math & Geometry",    description: "Increment a large integer represented as an array of digits.",                                 totalSubmissions: 4500000, acceptedSubmissions: 3200000 },
  { leetcodeId: 50,  slug: "lc-50-pow-x-n",                   title: "Pow(x, n)",                            difficulty: "MEDIUM", category: "Math",    pattern: "Math & Geometry",    description: "Implement pow(x, n) using fast exponentiation.",                                               totalSubmissions: 3700000, acceptedSubmissions: 2100000 },
  { leetcodeId: 43,  slug: "lc-43-multiply-strings",          title: "Multiply Strings",                     difficulty: "MEDIUM", category: "Math",    pattern: "Math & Geometry",    description: "Multiply two non-negative integers represented as strings.",                                   totalSubmissions: 2200000, acceptedSubmissions: 1300000 },
  { leetcodeId: 371, slug: "lc-371-sum-of-two-integers",      title: "Sum of Two Integers",                  difficulty: "MEDIUM", category: "Math",    pattern: "Math & Geometry",    description: "Calculate sum of two integers without using + or - operators.",                               totalSubmissions: 2300000, acceptedSubmissions: 1500000 },
  { leetcodeId: 2013, slug: "lc-2013-detect-squares",         title: "Detect Squares",                       difficulty: "MEDIUM", category: "Math",    pattern: "Math & Geometry",    description: "Count axis-aligned squares given a stream of points.",                                        totalSubmissions: 420000,  acceptedSubmissions: 270000 },

  // ── Bit Manipulation ──────────────────────────────────────────────────────
  { leetcodeId: 136, slug: "lc-136-single-number",            title: "Single Number",                        difficulty: "EASY",   category: "Array",   pattern: "Bit Manipulation",   description: "Find the element that appears only once using XOR.",                                          totalSubmissions: 7000000, acceptedSubmissions: 5700000 },
  { leetcodeId: 191, slug: "lc-191-hamming-weight",           title: "Number of 1 Bits",                     difficulty: "EASY",   category: "Math",    pattern: "Bit Manipulation",   description: "Return the number of set bits (Hamming weight) of an integer.",                               totalSubmissions: 3700000, acceptedSubmissions: 3000000 },
  { leetcodeId: 338, slug: "lc-338-counting-bits",            title: "Counting Bits",                        difficulty: "EASY",   category: "Dynamic Programming", pattern: "Bit Manipulation", description: "Return array of number of 1 bits for each number 0 to n.",            totalSubmissions: 3200000, acceptedSubmissions: 2700000 },
  { leetcodeId: 190, slug: "lc-190-reverse-bits",             title: "Reverse Bits",                         difficulty: "EASY",   category: "Math",    pattern: "Bit Manipulation",   description: "Reverse bits of a 32-bit unsigned integer.",                                                  totalSubmissions: 3200000, acceptedSubmissions: 2500000 },
  { leetcodeId: 268, slug: "lc-268-missing-number",           title: "Missing Number",                       difficulty: "EASY",   category: "Array",   pattern: "Bit Manipulation",   description: "Find the missing number in range [0, n].",                                                    totalSubmissions: 5300000, acceptedSubmissions: 4200000 },
  { leetcodeId: 7,   slug: "lc-7-reverse-integer",            title: "Reverse Integer",                      difficulty: "MEDIUM", category: "Math",    pattern: "Bit Manipulation",   description: "Reverse digits of a 32-bit signed integer.",                                                  totalSubmissions: 6900000, acceptedSubmissions: 3400000 },
];

export async function GET(req: NextRequest) {
  const { searchParams } = req.nextUrl;
  const pattern = searchParams.get("pattern") ?? "";
  const difficulty = searchParams.get("difficulty") ?? "";
  const search = searchParams.get("search") ?? "";

  try {
    // Seed on first load
    const existing = await prisma.codingChallenge.count();
    if (existing < PROBLEMS.length) {
      for (const p of PROBLEMS) {
        await prisma.codingChallenge.upsert({
          where: { leetcodeId: p.leetcodeId },
          create: p,
          update: { pattern: p.pattern, description: p.description, totalSubmissions: p.totalSubmissions, acceptedSubmissions: p.acceptedSubmissions },
        });
      }
    }

    const challenges = await prisma.codingChallenge.findMany({
      where: {
        ...(pattern ? { pattern: { contains: pattern, mode: "insensitive" } } : {}),
        ...(difficulty ? { difficulty: difficulty as "EASY" | "MEDIUM" | "HARD" } : {}),
        ...(search ? { title: { contains: search, mode: "insensitive" } } : {}),
      },
      orderBy: [
        { pattern: "asc" },
        { difficulty: "asc" },
        { leetcodeId: "asc" },
      ],
    });

    return NextResponse.json(challenges);
  } catch (err) {
    console.error("[coding/challenges]", err);
    return NextResponse.json({ error: "Failed to load challenges" }, { status: 500 });
  }
}
